CREATE TABLE TB_SUBESTACAO (
  ID_SUBESTACAO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CODIGO VARCHAR(3) NOT NULL UNIQUE, 
  NOME VARCHAR(100), 
  LATITUDE DECIMAL(15, 13) NOT NULL, 
  LONGITUDE DECIMAL(15, 13)
);

CREATE TABLE TB_REDE_MT (
  ID_REDE_MT INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ID_SUBESTACAO INT NOT NULL, 
  CODIGO VARCHAR(5) NOT NULL UNIQUE, 
  NOME VARCHAR(100), 
  TENSAO_NOMINAL DECIMAL(5, 2)
);

ALTER TABLE TB_REDE_MT 
ADD CONSTRAINT FK_SUBESTACAO_REDE_MT 
FOREIGN KEY (ID_SUBESTACAO) 
REFERENCES TB_SUBESTACAO (ID_SUBESTACAO) 
ON DELETE CASCADE;
